# Generated by Django 4.2.5 on 2023-09-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_account_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
