# Generated by Django 4.2.5 on 2023-09-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_accounts_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
