# Generated by Django 4.2.5 on 2023-09-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_rename_course_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='discription',
            new_name='description',
        ),
    ]
