# Generated by Django 4.2.5 on 2023-09-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_rename_discription_course_details_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
